---
- name: Configuring banner | issue.net
  copy:
      src: ../files/issue
      dest: /etc/issue.net
      owner: root
      group: root
      mode: 0644
      backup: yes
  tags:
      - banner
      - baseline

- name: Configuring banner | issue
  copy:
      src: ../files/issue
      dest: /etc/issue
      owner: root
      group: root
      mode: 0644
      backup: yes
  tags:
      - banner
      - baseline

- name: Configuring motd
  copy:
      src: ../files/motd
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
      backup: yes
  tags:
      - banner
      - baseline


