---

# Virt Configuration
- name: network | Destroy KVM bridge interface
  command: virsh net-destroy default
  ignore_errors: yes
  tags:
    - network
    - baseline

- name: network | Undefine KVM  bridge interface
  command: virsh net-undefine default 
  ignore_errors: yes
  tags:
    - network
    - baseline

- name: Disbale libvirtd
  service: 
    name: libvirtd 
    state: stopped 
    enabled: no
  ignore_errors: yes
  tags:
    - network
    - baseline

# disable NetworkManager Service
# - name: network | Disabling NetworkManager Service
#   service:
#     name: NetworkManager
#     state: stopped
#     enabled: no
#   tags: 
#     - NetworkManager
#     - network
 
